/**
 * Os emojis que o seletor oferece, em português.
 *
 * **Continua sendo uma lista à mão, e agora com motivo mais forte.** Um pacote
 * completo é o conjunto Unicode inteiro (mais de 3.700 caracteres) com os dados
 * de busca em inglês — dezenas de KB no bundle de uma tela que já carrega o
 * React Flow, para oferecer bandeiras e símbolos matemáticos a quem está
 * escrevendo "Oi, tudo bem?" no WhatsApp.
 *
 * O que mudou é o tamanho e a busca: eram 30 sem procura nenhuma, o que obrigava
 * a varrer a grade com o olho e não tinha o emoji que a pessoa queria. Agora são
 * os usados em conversa de atendimento, agrupados como no WhatsApp, e cada um
 * com as palavras em **português** — buscar "coração" tem que achar ❤️, e não
 * exigir "heart".
 *
 * Quem precisar de um que não está aqui continua colando do teclado do sistema,
 * que sempre funcionou.
 */
export type GrupoDeEmoji = {
  nome: string
  /** `[emoji, palavras de busca separadas por espaço]` */
  itens: [string, string][]
}

export const GRUPOS_DE_EMOJI: GrupoDeEmoji[] = [
  {
    nome: 'Rostos',
    itens: [
      ['😀', 'sorriso feliz alegre'],
      ['😃', 'sorriso feliz alegre'],
      ['😄', 'sorriso feliz rindo'],
      ['😁', 'sorriso dentes feliz'],
      ['😆', 'rindo gargalhada'],
      ['😅', 'rindo alivio suor'],
      ['🤣', 'gargalhada rolando rindo'],
      ['😂', 'chorando de rir lagrima'],
      ['🙂', 'sorriso leve'],
      ['🙃', 'de cabeca para baixo ironia'],
      ['😉', 'piscada'],
      ['😊', 'feliz timido sorriso'],
      ['😇', 'anjo santo'],
      ['🥰', 'apaixonado coracoes amor'],
      ['😍', 'apaixonado olhos coracao amor'],
      ['🤩', 'estrelas uau incrivel'],
      ['😘', 'beijo'],
      ['😗', 'beijo'],
      ['😚', 'beijo'],
      ['😋', 'delicia gostoso lingua'],
      ['😛', 'lingua'],
      ['😜', 'lingua piscada brincadeira'],
      ['🤪', 'maluco doido'],
      ['🤗', 'abraco'],
      ['🤭', 'ops risadinha'],
      ['🤫', 'silencio segredo'],
      ['🤔', 'pensando duvida'],
      ['🤐', 'boca fechada calado'],
      ['😐', 'neutro serio'],
      ['😑', 'sem expressao'],
      ['😶', 'sem boca calado'],
      ['🙄', 'revirando os olhos'],
      ['😏', 'malicioso sorrisinho'],
      ['😒', 'chateado desanimado'],
      ['😞', 'triste decepcionado'],
      ['😔', 'triste pensativo'],
      ['😟', 'preocupado'],
      ['😕', 'confuso'],
      ['🙁', 'triste'],
      ['😣', 'perseverando aflito'],
      ['😖', 'confuso aflito'],
      ['😫', 'cansado exausto'],
      ['😩', 'cansado chateado'],
      ['🥺', 'suplicante pedindo carinha'],
      ['😢', 'chorando triste lagrima'],
      ['😭', 'chorando muito triste'],
      ['😤', 'bufando raiva determinado'],
      ['😠', 'bravo raiva'],
      ['😡', 'furioso raiva vermelho'],
      ['🤯', 'explodindo cabeca chocado'],
      ['😳', 'surpreso envergonhado'],
      ['🥵', 'calor quente'],
      ['🥶', 'frio congelando'],
      ['😱', 'grito medo susto'],
      ['😨', 'medo assustado'],
      ['😰', 'ansioso suor medo'],
      ['😥', 'triste alivio'],
      ['😓', 'suor cansado'],
      ['🤥', 'mentira nariz'],
      ['😴', 'dormindo sono'],
      ['😪', 'sono cansado'],
      ['🤤', 'babando'],
      ['😷', 'mascara doente'],
      ['🤒', 'febre doente termometro'],
      ['🤕', 'machucado curativo'],
      ['🤧', 'espirro resfriado'],
      ['🥳', 'festa comemorando aniversario'],
      ['😎', 'oculos legal descolado'],
      ['🤓', 'nerd estudioso'],
      ['🧐', 'monoculo analisando'],
      ['😬', 'careta constrangido'],
      ['😮', 'surpreso boca aberta'],
      ['😯', 'surpreso'],
      ['😲', 'chocado espantado'],
      ['🤠', 'cowboy'],
      ['🥱', 'bocejo entediado'],
      ['😵', 'tonto'],
      ['🫠', 'derretendo'],
      ['🫡', 'continencia respeito'],
      ['🫢', 'mao na boca surpresa'],
      ['🤝', 'aperto de mao acordo negocio'],
    ],
  },
  {
    nome: 'Gestos e pessoas',
    itens: [
      ['👋', 'oi tchau aceno ola'],
      ['🤚', 'mao levantada'],
      ['🖐️', 'mao aberta'],
      ['✋', 'mao parada stop'],
      ['👌', 'ok joia perfeito'],
      ['🤌', 'dedos italiano'],
      ['🤏', 'pouco pequeno'],
      ['✌️', 'paz vitoria'],
      ['🤞', 'dedos cruzados sorte'],
      ['🤟', 'te amo mao'],
      ['🤙', 'me liga shaka'],
      ['👈', 'aponta esquerda'],
      ['👉', 'aponta direita'],
      ['👆', 'aponta cima'],
      ['👇', 'aponta baixo'],
      ['☝️', 'aponta cima atencao'],
      ['👍', 'joia positivo curtir like'],
      ['👎', 'negativo nao gostei'],
      ['✊', 'punho forca'],
      ['👊', 'soco punho'],
      ['👏', 'palmas aplauso parabens'],
      ['🙌', 'maos ao alto comemorar'],
      ['👐', 'maos abertas'],
      ['🤲', 'maos juntas pedido'],
      ['🙏', 'obrigado por favor oracao gratidao'],
      ['💪', 'forca musculo biceps'],
      ['🫶', 'coracao com as maos amor'],
      ['👀', 'olhos olhando'],
      ['🧑', 'pessoa'],
      ['👤', 'pessoa silhueta contato'],
      ['👥', 'pessoas grupo equipe'],
      ['👨‍💼', 'homem trabalho profissional'],
      ['👩‍💼', 'mulher trabalho profissional'],
      ['🧑‍💻', 'pessoa computador suporte'],
      ['👶', 'bebe'],
      ['🧒', 'crianca'],
      ['👵', 'idosa'],
      ['👴', 'idoso'],
      ['🚶', 'andando caminhando'],
      ['🏃', 'correndo rapido'],
      ['💃', 'dancando festa'],
      ['🕺', 'dancando festa'],
    ],
  },
  {
    nome: 'Coração e símbolos',
    itens: [
      ['❤️', 'coracao amor vermelho'],
      ['🧡', 'coracao laranja'],
      ['💛', 'coracao amarelo'],
      ['💚', 'coracao verde'],
      ['💙', 'coracao azul'],
      ['💜', 'coracao roxo'],
      ['🖤', 'coracao preto'],
      ['🤍', 'coracao branco'],
      ['💔', 'coracao partido'],
      ['💕', 'coracoes amor'],
      ['💖', 'coracao brilhante amor'],
      ['💗', 'coracao crescendo'],
      ['💘', 'coracao flecha paixao'],
      ['💞', 'coracoes girando'],
      ['💯', 'cem nota maxima top'],
      ['✅', 'certo confirmado check ok'],
      ['☑️', 'marcado check'],
      ['✔️', 'certo check'],
      ['❌', 'errado cancelar x'],
      ['⭕', 'circulo vermelho'],
      ['❗', 'exclamacao atencao'],
      ['❓', 'pergunta duvida'],
      ['⚠️', 'atencao aviso cuidado'],
      ['🚫', 'proibido'],
      ['🔴', 'bolinha vermelha'],
      ['🟢', 'bolinha verde'],
      ['🟡', 'bolinha amarela'],
      ['🔵', 'bolinha azul'],
      ['⭐', 'estrela favorito'],
      ['🌟', 'estrela brilhante'],
      ['✨', 'brilho novidade'],
      ['🎉', 'festa comemoracao parabens'],
      ['🎊', 'confete festa'],
      ['🔥', 'fogo bombando quente'],
      ['💥', 'explosao'],
      ['⚡', 'raio rapido energia'],
      ['🏆', 'trofeu premio'],
      ['🥇', 'primeiro lugar medalha ouro'],
      ['🎯', 'alvo meta objetivo'],
      ['🔝', 'topo melhor'],
      ['🆕', 'novo'],
      ['🆗', 'ok'],
      ['🔒', 'cadeado fechado seguro'],
      ['🔓', 'cadeado aberto'],
      ['♻️', 'reciclar'],
      ['➡️', 'seta direita'],
      ['⬅️', 'seta esquerda'],
      ['⬆️', 'seta cima'],
      ['⬇️', 'seta baixo'],
    ],
  },
  {
    nome: 'Trabalho e contato',
    itens: [
      ['📱', 'celular telefone whatsapp'],
      ['📞', 'telefone ligar chamada'],
      ['☎️', 'telefone fixo'],
      ['📲', 'celular chamada'],
      ['💬', 'balao mensagem conversa chat'],
      ['🗨️', 'balao fala'],
      ['💭', 'balao pensamento'],
      ['📧', 'email mensagem'],
      ['✉️', 'envelope email carta'],
      ['📩', 'email chegando'],
      ['📅', 'calendario data agenda'],
      ['📆', 'calendario agenda'],
      ['🗓️', 'calendario agenda'],
      ['⏰', 'despertador horario alarme'],
      ['⏳', 'ampulheta esperando prazo'],
      ['🕒', 'relogio hora'],
      ['📍', 'localizacao endereco mapa pin'],
      ['🗺️', 'mapa'],
      ['🏠', 'casa endereco'],
      ['🏢', 'predio escritorio empresa'],
      ['🏥', 'hospital clinica'],
      ['🏪', 'loja'],
      ['🛒', 'carrinho compras pedido'],
      ['🛍️', 'sacola compras'],
      ['💰', 'dinheiro saco valor'],
      ['💵', 'dinheiro nota'],
      ['💳', 'cartao pagamento credito'],
      ['🧾', 'recibo nota fiscal'],
      ['📊', 'grafico barras relatorio'],
      ['📈', 'grafico subindo crescimento'],
      ['📉', 'grafico caindo queda'],
      ['📋', 'prancheta lista checklist'],
      ['📝', 'anotar escrever formulario'],
      ['📄', 'documento arquivo pdf'],
      ['📁', 'pasta arquivo'],
      ['📎', 'clipe anexo'],
      ['🔗', 'link endereco url'],
      ['🔍', 'lupa buscar procurar'],
      ['💡', 'ideia dica lampada'],
      ['🔔', 'sino aviso notificacao'],
      ['📣', 'megafone anuncio divulgacao'],
      ['📢', 'alto falante anuncio'],
      ['🚀', 'foguete lancamento rapido'],
      ['⚙️', 'engrenagem configuracao ajuste'],
      ['🔧', 'chave ferramenta conserto'],
      ['🖥️', 'computador monitor'],
      ['💻', 'notebook computador'],
      ['🖨️', 'impressora'],
      ['📷', 'camera foto'],
      ['📸', 'foto flash'],
      ['🎥', 'camera video filmagem'],
      ['🎬', 'claquete video'],
      ['🎤', 'microfone audio'],
      ['🎧', 'fone audio'],
      ['🔊', 'som alto audio'],
      ['🚗', 'carro'],
      ['🏍️', 'moto entrega'],
      ['🚚', 'caminhao entrega frete'],
      ['✈️', 'aviao viagem'],
      ['📦', 'caixa pacote entrega encomenda'],
    ],
  },
  {
    nome: 'Comida e lazer',
    itens: [
      ['☕', 'cafe'],
      ['🍵', 'cha'],
      ['🥤', 'refrigerante bebida copo'],
      ['🍺', 'cerveja'],
      ['🍷', 'vinho'],
      ['🥂', 'brinde comemoracao'],
      ['🍰', 'bolo doce sobremesa'],
      ['🎂', 'bolo aniversario'],
      ['🍫', 'chocolate'],
      ['🍪', 'biscoito cookie'],
      ['🍕', 'pizza'],
      ['🍔', 'hamburguer lanche'],
      ['🌭', 'cachorro quente'],
      ['🍟', 'batata frita'],
      ['🥗', 'salada saudavel'],
      ['🍎', 'maca fruta'],
      ['🍓', 'morango fruta'],
      ['🍇', 'uva fruta'],
      ['🥑', 'abacate'],
      ['🍞', 'pao'],
      ['🧀', 'queijo'],
      ['🍽️', 'prato talher refeicao'],
      ['⚽', 'futebol bola'],
      ['🏀', 'basquete'],
      ['🏐', 'volei'],
      ['🎾', 'tenis'],
      ['🏋️', 'academia treino musculacao'],
      ['🧘', 'yoga meditacao pilates'],
      ['🤸', 'alongamento exercicio'],
      ['🏊', 'natacao'],
      ['🚴', 'bicicleta ciclismo'],
      ['🎵', 'musica nota'],
      ['🎶', 'musica notas'],
      ['🎁', 'presente brinde'],
      ['🌹', 'rosa flor'],
      ['🌸', 'flor'],
      ['🌻', 'girassol flor'],
      ['🌱', 'planta muda crescimento'],
      ['🐶', 'cachorro pet'],
      ['🐱', 'gato pet'],
      ['🐾', 'patinhas pet animal'],
      ['☀️', 'sol dia'],
      ['🌙', 'lua noite'],
      ['🌈', 'arco iris'],
      ['💧', 'gota agua'],
      ['❄️', 'neve frio'],
    ],
  },
]

/** Todos os emojis numa lista só — é o que a busca varre. */
export const TODOS_OS_EMOJIS: [string, string][] = GRUPOS_DE_EMOJI.flatMap((g) => g.itens)
